// Run with Bun from any directory. Checked-in output works on Workers without a
// runtime filesystem or bundler. --check is suitable for local/CI verification.
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { bundleLicenseBanner } from "../../../scripts/bundle-licenses";
const base = new URL("../../../", import.meta.url);
const sources = [
  "browser-capture-entry.ts",
  "browser-capture.ts",
  "capture-gradients.ts",
  "effects.ts",
  "capture-effects.ts",
  "rasterize-element.ts",
  "raster-tiles.ts",
  "capture-source.ts",
  "document-defaults.ts",
];
const sourceHash = createHash("sha256");
for (const source of sources)
  sourceHash.update(await Bun.file(new URL(`packages/design/${source}`, base)).text());
const bundled = await Bun.build({
  entrypoints: [fileURLToPath(new URL("packages/design/browser-capture-entry.ts", base))],
  target: "browser",
  format: "iife",
  minify: true,
  metafile: true,
});
if (!bundled.success) throw new Error(String(bundled.logs));
const script = (await bundleLicenseBanner(bundled)) + (await bundled.outputs[0]!.text());
const output = `// Generated by scripts/build-browser-capture.ts; do not edit.\nexport const browserCaptureSourceHash = ${JSON.stringify(sourceHash.digest("hex"))};\nexport const browserCaptureScript = ${JSON.stringify(script)};\n`;
const destination = new URL("apps/web/lib/mcp/browser-capture.generated.ts", base);
if (process.argv.includes("--check")) {
  if ((await Bun.file(destination).text()) !== output)
    throw new Error(
      "Browser capture bundle is stale. Run bun apps/web/scripts/build-browser-capture.ts.",
    );
  console.log("Browser capture bundle is current.");
} else {
  await Bun.write(destination, output);
  console.log(`Built MCP browser capture script (${script.length} characters).`);
}
