import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { bundleLicenseBanner } from "../../../scripts/bundle-licenses";

const workspace = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const result = await Bun.build({
  entrypoints: [resolve(workspace, "lib/design/code-runtime.tsx")],
  target: "browser",
  format: "esm",
  minify: true,
  external: ["react", "react/jsx-runtime"],
  metafile: true,
});
if (!result.success) throw new Error(result.logs.join("\n"));
const source = (await bundleLicenseBanner(result)) + (await result.outputs[0].text());
const contents = `// Generated by scripts/generate-code-runtime.ts. Do not edit.\nexport const codeRuntimeHash = ${JSON.stringify(createHash("sha256").update(source).digest("hex"))};\nexport const codeRuntimeSource = ${JSON.stringify(source)};\n`;
const target = resolve(workspace, "lib/design/code-runtime.generated.ts");
if (process.argv.includes("--check")) {
  if ((await Bun.file(target).text()) !== contents)
    throw new Error("Code runtime is stale. Run bun apps/web/scripts/generate-code-runtime.ts.");
} else await Bun.write(target, contents);
