import { gzipSync } from "node:zlib";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { bundleLicenseBanner } from "../../../scripts/bundle-licenses";

const workspace = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const result = await Bun.build({
  entrypoints: [resolve(workspace, "lib/design/visual-preview-runtime.tsx")],
  target: "browser",
  format: "iife",
  minify: true,
  define: { "process.env.NODE_ENV": JSON.stringify("production") },
  metafile: true,
});
if (!result.success) throw new Error(result.logs.join("\n"));
const notices = await bundleLicenseBanner(result);
const source = notices + (await result.outputs[0].text());
const gzip = gzipSync(source, { level: 9 });
// Gzip's OS header differs between macOS and Linux despite identical payloads.
// Use the format's "unknown" value to make committed artifacts reproducible.
gzip[9] = 255;
const compressed = gzip.toString("base64");
// Keep the notices readable in saved HTML as well as inside the gzip payload.
const bootstrap = `${notices}(async()=>{const bytes=Uint8Array.from(atob("${compressed}"),c=>c.charCodeAt(0));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"));const script=document.createElement("script");script.textContent=await new Response(stream).text();document.body.appendChild(script)})().catch(error=>{console.error("Could not load design preview",error);document.getElementById("tidy-preview").textContent="Could not load design preview."});`;
const contents = `// Generated by scripts/generate-visual-preview-runtime.ts. Do not edit.\nexport const visualPreviewRuntimeHash = ${JSON.stringify(createHash("sha256").update(source).digest("hex"))};\nexport const visualPreviewRuntime = ${JSON.stringify(bootstrap)};\n`;
const target = resolve(workspace, "lib/design/visual-preview-runtime.generated.ts");
if (process.argv.includes("--check")) {
  if ((await Bun.file(target).text()) !== contents)
    throw new Error(
      "Visual preview runtime is stale. Run bun apps/web/scripts/generate-visual-preview-runtime.ts.",
    );
} else await Bun.write(target, contents);
