export const bindingKinds = {
  width: "dimension",
  height: "dimension",
  minWidth: "dimension",
  maxWidth: "dimension",
  minHeight: "dimension",
  maxHeight: "dimension",
  radius: "radius",
  radiusTopLeft: "radius",
  radiusTopRight: "radius",
  radiusBottomLeft: "radius",
  radiusBottomRight: "radius",
  gap: "spacing",
  columnGap: "spacing",
  rowGap: "spacing",
  padding: "spacing",
  paddingTop: "spacing",
  paddingRight: "spacing",
  paddingBottom: "spacing",
  paddingLeft: "spacing",
  fontSize: "dimension",
  fontWeight: "number",
  lineHeight: "number",
  lineHeightPx: "dimension",
  letterSpacing: "spacing",
  paragraphSpacing: "spacing",
  textStyle: "typography",
} as const;
export type TokenBinding = keyof typeof bindingKinds;
